import type { Dish } from "@/types"

export const catalog: Dish[] = [
    {
        id: "pizza",
        name: "pizza",
        cuisines: ["Italian"],
        meal_type: "main_course",
        ingredients: ["pizza dough", "tomato sauce", "mozzarella", "basil", "olive oil"],
    },
    {
        id: "lasagna",
        name: "lasagna",
        cuisines: ["Italian"],
        meal_type: "main_course",
        ingredients: ["pasta sheets", "minced meat", "tomato sauce", "bechamel", "parmesan"],
    },
    {
        id: "risotto",
        name: "risotto",
        cuisines: ["Italian"],
        meal_type: "rice_dish",
        ingredients: ["arborio rice", "broth", "butter", "parmesan", "mushrooms"],
    },
    {
        id: "gnocchi",
        name: "gnocchi",
        cuisines: ["Italian"],
        meal_type: "main_course",
        ingredients: ["potatoes", "flour", "butter", "parmesan", "sage"],
    },
    {
        id: "spaghetti-carbonara",
        name: "spaghetti carbonara",
        cuisines: ["Italian"],
        meal_type: "noodle_dish",
        ingredients: ["spaghetti", "egg", "pancetta", "pecorino", "black pepper"],
    },
    {
        id: "ravioli",
        name: "ravioli",
        cuisines: ["Italian"],
        meal_type: "noodle_dish",
        ingredients: ["pasta dough", "ricotta", "spinach", "butter", "parmesan"],
    },
    {
        id: "focaccia",
        name: "focaccia",
        cuisines: ["Italian"],
        meal_type: "bread",
        ingredients: ["flour", "olive oil", "yeast", "rosemary", "sea salt"],
    },
    {
        id: "tiramisu",
        name: "tiramisu",
        cuisines: ["Italian"],
        meal_type: "dessert",
        ingredients: ["mascarpone", "espresso", "ladyfingers", "cocoa", "egg"],
    },

    {
        id: "butter-chicken",
        name: "butter chicken",
        cuisines: ["Indian"],
        meal_type: "curry",
        ingredients: ["chicken", "tomato", "butter", "cream", "spices"],
    },
    {
        id: "chicken-tikka-masala",
        name: "chicken tikka masala",
        cuisines: ["Indian"],
        meal_type: "curry",
        ingredients: ["chicken", "yogurt", "tomato", "cream", "spices"],
    },
    {
        id: "palak-paneer",
        name: "palak paneer",
        cuisines: ["Indian"],
        meal_type: "curry",
        ingredients: ["spinach", "paneer", "cream", "ginger", "spices"],
    },
    {
        id: "chole-bhature",
        name: "chole bhature",
        cuisines: ["Indian"],
        meal_type: "street_food",
        ingredients: ["chickpeas", "flour", "yogurt", "onion", "spices"],
    },
    {
        id: "dosa",
        name: "dosa",
        cuisines: ["Indian"],
        meal_type: "breakfast",
        ingredients: ["rice batter", "lentils", "potato", "curry leaves", "ghee"],
    },
    {
        id: "pav-bhaji",
        name: "pav bhaji",
        cuisines: ["Indian"],
        meal_type: "street_food",
        ingredients: ["mixed vegetables", "butter", "pav", "tomato", "spices"],
    },
    {
        id: "rajma-chawal",
        name: "rajma chawal",
        cuisines: ["Indian"],
        meal_type: "rice_dish",
        ingredients: ["kidney beans", "rice", "onion", "tomato", "spices"],
    },
    {
        id: "dal-makhani",
        name: "dal makhani",
        cuisines: ["Indian"],
        meal_type: "curry",
        ingredients: ["black lentils", "kidney beans", "butter", "cream", "tomato"],
    },
    {
        id: "biryani",
        name: "biryani",
        cuisines: ["Indian"],
        meal_type: "rice_dish",
        ingredients: ["basmati rice", "meat", "yogurt", "fried onion", "spices"],
    },
    {
        id: "samosa",
        name: "samosa",
        cuisines: ["Indian"],
        meal_type: "snack",
        ingredients: ["potato", "peas", "flour", "cumin", "chili"],
    },
    {
        id: "aloo-paratha",
        name: "aloo paratha",
        cuisines: ["Indian"],
        meal_type: "breakfast",
        ingredients: ["wheat flour", "potato", "butter", "coriander", "spices"],
    },
    {
        id: "chaat",
        name: "chaat",
        cuisines: ["Indian"],
        meal_type: "street_food",
        ingredients: ["potato", "yogurt", "tamarind chutney", "sev", "spices"],
    },
    {
        id: "paneer-tikka",
        name: "paneer tikka",
        cuisines: ["Indian"],
        meal_type: "grill",
        ingredients: ["paneer", "yogurt", "bell pepper", "onion", "spices"],
    },
    {
        id: "shahi-paneer",
        name: "shahi paneer",
        cuisines: ["Indian"],
        meal_type: "curry",
        ingredients: ["paneer", "tomato", "cream", "cashew", "spices"],
    },
    {
        id: "matar-paneer",
        name: "matar paneer",
        cuisines: ["Indian"],
        meal_type: "curry",
        ingredients: ["paneer", "peas", "tomato", "onion", "spices"],
    },
    {
        id: "malai-kofta",
        name: "malai kofta",
        cuisines: ["Indian"],
        meal_type: "curry",
        ingredients: ["paneer", "potato", "cream", "tomato", "spices"],
    },
    {
        id: "kadhi-chawal",
        name: "kadhi chawal",
        cuisines: ["Indian"],
        meal_type: "rice_dish",
        ingredients: ["yogurt", "gram flour", "rice", "curry leaves", "spices"],
    },
    {
        id: "sarson-da-saag",
        name: "sarson da saag",
        cuisines: ["Indian"],
        meal_type: "curry",
        ingredients: ["mustard greens", "spinach", "ginger", "butter", "cornmeal"],
    },
    {
        id: "amritsari-kulcha",
        name: "amritsari kulcha",
        cuisines: ["Indian"],
        meal_type: "bread",
        ingredients: ["flour", "potato", "coriander", "butter", "onion"],
    },
    {
        id: "rogan-josh",
        name: "rogan josh",
        cuisines: ["Indian"],
        meal_type: "curry",
        ingredients: ["lamb", "yogurt", "onion", "fennel", "spices"],
    },
    {
        id: "jalebi",
        name: "jalebi",
        cuisines: ["Indian"],
        meal_type: "dessert",
        ingredients: ["flour", "yogurt", "sugar syrup", "saffron", "ghee"],
    },
    {
        id: "gulab-jamun",
        name: "gulab jamun",
        cuisines: ["Indian"],
        meal_type: "dessert",
        ingredients: ["milk solids", "flour", "sugar syrup", "cardamom", "ghee"],
    },
    {
        id: "rasmalai",
        name: "rasmalai",
        cuisines: ["Indian"],
        meal_type: "dessert",
        ingredients: ["paneer", "milk", "sugar", "cardamom", "saffron"],
    },
    {
        id: "kheer",
        name: "kheer",
        cuisines: ["Indian"],
        meal_type: "dessert",
        ingredients: ["rice", "milk", "sugar", "cardamom", "nuts"],
    },
    {
        id: "rabri",
        name: "rabri",
        cuisines: ["Indian"],
        meal_type: "dessert",
        ingredients: ["milk", "sugar", "cardamom", "saffron", "nuts"],
    },

    {
        id: "hummus",
        name: "hummus",
        cuisines: ["Lebanese", "Middle Eastern"],
        meal_type: "dip",
        ingredients: ["chickpeas", "tahini", "lemon", "garlic", "olive oil"],
    },
    {
        id: "falafel",
        name: "falafel",
        cuisines: ["Lebanese", "Middle Eastern"],
        meal_type: "snack",
        ingredients: ["chickpeas", "parsley", "garlic", "cumin", "onion"],
    },
    {
        id: "shawarma",
        name: "shawarma",
        cuisines: ["Lebanese", "Middle Eastern"],
        meal_type: "sandwich_wrap",
        ingredients: ["chicken", "pita", "garlic sauce", "pickles", "spices"],
    },
    {
        id: "fattoush",
        name: "fattoush",
        cuisines: ["Lebanese", "Middle Eastern"],
        meal_type: "salad",
        ingredients: ["lettuce", "tomato", "cucumber", "pita chips", "sumac"],
    },
    {
        id: "tabbouleh",
        name: "tabbouleh",
        cuisines: ["Lebanese", "Middle Eastern"],
        meal_type: "salad",
        ingredients: ["parsley", "bulgur", "tomato", "mint", "lemon"],
    },
    {
        id: "kibbeh",
        name: "kibbeh",
        cuisines: ["Lebanese", "Middle Eastern"],
        meal_type: "snack",
        ingredients: ["bulgur", "minced meat", "onion", "pine nuts", "spices"],
    },
    {
        id: "kofta-kebab",
        name: "kofta kebab",
        cuisines: ["Middle Eastern"],
        meal_type: "grill",
        ingredients: ["minced meat", "onion", "parsley", "cumin", "spices"],
    },
    {
        id: "shakshuka",
        name: "shakshuka",
        cuisines: ["Middle Eastern"],
        meal_type: "breakfast",
        ingredients: ["eggs", "tomato", "bell pepper", "onion", "spices"],
    },

    {
        id: "burger",
        name: "burger",
        cuisines: ["American"],
        meal_type: "sandwich_wrap",
        ingredients: ["beef patty", "bun", "lettuce", "tomato", "cheese"],
    },
    {
        id: "fried-chicken",
        name: "fried chicken",
        cuisines: ["American"],
        meal_type: "main_course",
        ingredients: ["chicken", "flour", "buttermilk", "paprika", "oil"],
    },
    {
        id: "mac-and-cheese",
        name: "mac and cheese",
        cuisines: ["American"],
        meal_type: "main_course",
        ingredients: ["macaroni", "cheddar", "milk", "butter", "breadcrumbs"],
    },
    {
        id: "barbecue-ribs",
        name: "barbecue ribs",
        cuisines: ["American"],
        meal_type: "grill",
        ingredients: ["pork ribs", "barbecue sauce", "garlic", "paprika", "brown sugar"],
    },
    {
        id: "hot-dog",
        name: "hot dog",
        cuisines: ["American"],
        meal_type: "sandwich_wrap",
        ingredients: ["sausage", "bun", "mustard", "ketchup", "onion"],
    },
    {
        id: "pancakes",
        name: "pancakes",
        cuisines: ["American"],
        meal_type: "breakfast",
        ingredients: ["flour", "milk", "egg", "butter", "maple syrup"],
    },
    {
        id: "grilled-cheese-sandwich",
        name: "grilled cheese sandwich",
        cuisines: ["American"],
        meal_type: "sandwich_wrap",
        ingredients: ["bread", "cheese", "butter"],
    },

    {
        id: "sushi",
        name: "sushi",
        cuisines: ["Japanese"],
        meal_type: "rice_dish",
        ingredients: ["sushi rice", "nori", "seafood", "vinegar", "soy sauce"],
    },
    {
        id: "ramen",
        name: "ramen",
        cuisines: ["Japanese"],
        meal_type: "noodle_dish",
        ingredients: ["noodles", "broth", "pork", "egg", "scallion"],
    },
    {
        id: "okonomiyaki",
        name: "okonomiyaki",
        cuisines: ["Japanese"],
        meal_type: "main_course",
        ingredients: ["cabbage", "flour", "egg", "pork", "sauce"],
    },
    {
        id: "katsu-curry",
        name: "katsu curry",
        cuisines: ["Japanese"],
        meal_type: "curry",
        ingredients: ["breaded cutlet", "curry sauce", "rice", "flour", "egg"],
    },
    {
        id: "onigiri",
        name: "onigiri",
        cuisines: ["Japanese"],
        meal_type: "snack",
        ingredients: ["rice", "nori", "salmon", "sesame", "salt"],
    },

    {
        id: "tacos",
        name: "tacos",
        cuisines: ["Mexican"],
        meal_type: "street_food",
        ingredients: ["tortillas", "meat", "onion", "cilantro", "salsa"],
    },
    {
        id: "burrito",
        name: "burrito",
        cuisines: ["Mexican"],
        meal_type: "sandwich_wrap",
        ingredients: ["tortilla", "rice", "beans", "meat", "salsa"],
    },
    {
        id: "quesadilla",
        name: "quesadilla",
        cuisines: ["Mexican"],
        meal_type: "snack",
        ingredients: ["tortilla", "cheese", "onion", "peppers", "salsa"],
    },
    {
        id: "guacamole",
        name: "guacamole",
        cuisines: ["Mexican"],
        meal_type: "dip",
        ingredients: ["avocado", "lime", "onion", "cilantro", "chili"],
    },
    {
        id: "elote",
        name: "elote",
        cuisines: ["Mexican"],
        meal_type: "street_food",
        ingredients: ["corn", "mayo", "cheese", "chili", "lime"],
    },
    {
        id: "nachos",
        name: "nachos",
        cuisines: ["Mexican"],
        meal_type: "snack",
        ingredients: ["tortilla chips", "cheese", "beans", "jalapeno", "salsa"],
    },

    {
        id: "fresh-spring-rolls",
        name: "fresh spring rolls",
        cuisines: ["Vietnamese"],
        meal_type: "snack",
        ingredients: ["rice paper", "herbs", "shrimp", "vermicelli", "lettuce"],
    },

    {
        id: "dumplings",
        name: "dumplings",
        cuisines: ["Chinese"],
        meal_type: "snack",
        ingredients: ["flour", "minced meat", "cabbage", "ginger", "soy sauce"],
    },
    {
        id: "chow-mein",
        name: "chow mein",
        cuisines: ["Chinese"],
        meal_type: "noodle_dish",
        ingredients: ["noodles", "vegetables", "soy sauce", "meat", "scallion"],
    },
    {
        id: "sweet-and-sour-pork",
        name: "sweet and sour pork",
        cuisines: ["Chinese"],
        meal_type: "main_course",
        ingredients: ["pork", "bell pepper", "pineapple", "vinegar", "sauce"],
    },
    {
        id: "hot-pot",
        name: "hot pot",
        cuisines: ["Chinese"],
        meal_type: "soup",
        ingredients: ["broth", "meat", "tofu", "vegetables", "noodles"],
    },
    {
        id: "wonton-soup",
        name: "wonton soup",
        cuisines: ["Chinese"],
        meal_type: "soup",
        ingredients: ["wontons", "broth", "scallion", "ginger", "sesame oil"],
    },
    {
        id: "fried-rice",
        name: "fried rice",
        cuisines: ["Chinese"],
        meal_type: "rice_dish",
        ingredients: ["rice", "egg", "vegetables", "soy sauce", "scallion"],
    },

    {
        id: "croissant",
        name: "croissant",
        cuisines: ["French"],
        meal_type: "breakfast",
        ingredients: ["flour", "butter", "yeast", "milk", "sugar"],
    },
    {
        id: "crepes",
        name: "crepes",
        cuisines: ["French"],
        meal_type: "breakfast",
        ingredients: ["flour", "milk", "egg", "butter", "sugar"],
    },
    {
        id: "ratatouille",
        name: "ratatouille",
        cuisines: ["French"],
        meal_type: "main_course",
        ingredients: ["eggplant", "zucchini", "tomato", "bell pepper", "herbs"],
    },

    {
        id: "doner-kebab",
        name: "doner kebab",
        cuisines: ["Turkish"],
        meal_type: "sandwich_wrap",
        ingredients: ["meat", "pita", "tomato", "onion", "yogurt sauce"],
    },
    {
        id: "gyros",
        name: "gyros",
        cuisines: ["Greek"],
        meal_type: "sandwich_wrap",
        ingredients: ["pork", "pita", "tomato", "onion", "tzatziki"],
    },

    {
        id: "fish-and-chips",
        name: "fish and chips",
        cuisines: ["British"],
        meal_type: "main_course",
        ingredients: ["fish", "potato", "flour", "vinegar", "tartar sauce"],
    },
    {
        id: "english-breakfast",
        name: "english breakfast",
        cuisines: ["British"],
        meal_type: "breakfast",
        ingredients: ["eggs", "sausage", "beans", "toast", "mushrooms"],
    },
]

export const catalogById = new Map(catalog.map((item) => [item.id, item]))
