import type { Dish } from "@/types"

export const catalog: Dish[] = [
    {
        id: "pizza",
        name: "pizza",
        cuisines: ["Italian"],
        meal_type: "main_course",
        ingredients: ["pizza dough", "tomato sauce", "mozzarella", "basil", "olive oil"],
        popularity: "common",
        flavor_profile: ["savory", "cheesy", "tomato-rich"],
    },
    {
        id: "lasagna",
        name: "lasagna",
        cuisines: ["Italian"],
        meal_type: "main_course",
        ingredients: ["pasta sheets", "minced meat", "tomato sauce", "bechamel", "parmesan"],
        popularity: "common",
        flavor_profile: ["savory", "baked", "rich"],
    },
    {
        id: "risotto",
        name: "risotto",
        cuisines: ["Italian"],
        meal_type: "rice_dish",
        ingredients: ["arborio rice", "broth", "butter", "parmesan", "mushrooms"],
        popularity: "moderate",
        flavor_profile: ["creamy", "savory", "earthy"],
    },
    {
        id: "gnocchi",
        name: "gnocchi",
        cuisines: ["Italian"],
        meal_type: "main_course",
        ingredients: ["potatoes", "flour", "butter", "parmesan", "sage"],
        popularity: "moderate",
        flavor_profile: ["soft", "buttery", "savory"],
    },
    {
        id: "spaghetti-carbonara",
        name: "spaghetti carbonara",
        cuisines: ["Italian"],
        meal_type: "noodle_dish",
        ingredients: ["spaghetti", "egg", "pancetta", "pecorino", "black pepper"],
        popularity: "common",
        flavor_profile: ["creamy", "salty", "peppery"],
    },
    {
        id: "ravioli",
        name: "ravioli",
        cuisines: ["Italian"],
        meal_type: "noodle_dish",
        ingredients: ["pasta dough", "ricotta", "spinach", "butter", "parmesan"],
        popularity: "moderate",
        flavor_profile: ["creamy", "herby", "savory"],
    },
    {
        id: "focaccia",
        name: "focaccia",
        cuisines: ["Italian"],
        meal_type: "bread",
        ingredients: ["flour", "olive oil", "yeast", "rosemary", "sea salt"],
        popularity: "moderate",
        flavor_profile: ["herby", "salty", "olive-oil-rich"],
    },
    {
        id: "tiramisu",
        name: "tiramisu",
        cuisines: ["Italian"],
        meal_type: "dessert",
        ingredients: ["mascarpone", "espresso", "ladyfingers", "cocoa", "egg"],
        popularity: "common",
        flavor_profile: ["sweet", "coffee", "creamy"],
    },

    {
        id: "butter-chicken",
        name: "butter chicken",
        cuisines: ["North Indian"],
        meal_type: "curry",
        ingredients: ["chicken", "tomato", "butter", "cream", "spices"],
        popularity: "common",
        flavor_profile: ["creamy", "mildly-spiced", "tomato-rich"],
    },
    {
        id: "chicken-tikka-masala",
        name: "chicken tikka masala",
        cuisines: ["Indian restaurant"],
        meal_type: "curry",
        ingredients: ["chicken", "yogurt", "tomato", "cream", "spices"],
        popularity: "common",
        flavor_profile: ["creamy", "spiced", "tomato-rich"],
    },
    {
        id: "palak-paneer",
        name: "palak paneer",
        cuisines: ["North Indian"],
        meal_type: "curry",
        ingredients: ["spinach", "paneer", "cream", "ginger", "spices"],
        popularity: "common",
        flavor_profile: ["creamy", "earthy", "spiced"],
    },
    {
        id: "chole-bhature",
        name: "chole bhature",
        cuisines: ["Punjabi"],
        meal_type: "street_food",
        ingredients: ["chickpeas", "flour", "yogurt", "onion", "spices"],
        popularity: "distinctive",
        flavor_profile: ["spiced", "tangy", "hearty"],
    },
    {
        id: "dosa",
        name: "dosa",
        cuisines: ["South Indian"],
        meal_type: "breakfast",
        ingredients: ["rice batter", "lentils", "potato", "curry leaves", "ghee"],
        popularity: "distinctive",
        flavor_profile: ["crisp", "tangy", "savory"],
    },
    {
        id: "pav-bhaji",
        name: "pav bhaji",
        cuisines: ["Maharashtrian", "Mumbai street food"],
        meal_type: "street_food",
        ingredients: ["mixed vegetables", "butter", "pav", "tomato", "spices"],
        popularity: "distinctive",
        flavor_profile: ["buttery", "spiced", "tangy"],
    },
    {
        id: "rajma-chawal",
        name: "rajma chawal",
        cuisines: ["Punjabi", "North Indian"],
        meal_type: "rice_dish",
        ingredients: ["kidney beans", "rice", "onion", "tomato", "spices"],
        popularity: "moderate",
        flavor_profile: ["hearty", "spiced", "comforting"],
    },
    {
        id: "dal-makhani",
        name: "dal makhani",
        cuisines: ["Punjabi"],
        meal_type: "curry",
        ingredients: ["black lentils", "kidney beans", "butter", "cream", "tomato"],
        popularity: "common",
        flavor_profile: ["creamy", "smoky", "hearty"],
    },
    {
        id: "biryani",
        name: "biryani",
        cuisines: ["Hyderabadi", "Awadhi"],
        meal_type: "rice_dish",
        ingredients: ["basmati rice", "meat", "yogurt", "fried onion", "spices"],
        popularity: "common",
        flavor_profile: ["aromatic", "spiced", "rich"],
    },
    {
        id: "samosa",
        name: "samosa",
        cuisines: ["North Indian"],
        meal_type: "snack",
        ingredients: ["potato", "peas", "flour", "cumin", "chili"],
        popularity: "common",
        flavor_profile: ["crispy", "spiced", "savory"],
    },
    {
        id: "aloo-paratha",
        name: "aloo paratha",
        cuisines: ["Punjabi"],
        meal_type: "breakfast",
        ingredients: ["wheat flour", "potato", "butter", "coriander", "spices"],
        popularity: "moderate",
        flavor_profile: ["buttery", "spiced", "hearty"],
    },
    {
        id: "chaat",
        name: "chaat",
        cuisines: ["Indian street food"],
        meal_type: "street_food",
        ingredients: ["potato", "yogurt", "tamarind chutney", "sev", "spices"],
        popularity: "distinctive",
        flavor_profile: ["tangy", "crunchy", "spiced"],
    },
    {
        id: "paneer-tikka",
        name: "paneer tikka",
        cuisines: ["North Indian"],
        meal_type: "grill",
        ingredients: ["paneer", "yogurt", "bell pepper", "onion", "spices"],
        popularity: "moderate",
        flavor_profile: ["smoky", "spiced", "tangy"],
    },
    {
        id: "shahi-paneer",
        name: "shahi paneer",
        cuisines: ["Mughlai", "North Indian"],
        meal_type: "curry",
        ingredients: ["paneer", "tomato", "cream", "cashew", "spices"],
        popularity: "moderate",
        flavor_profile: ["creamy", "mildly-spiced", "rich"],
    },
    {
        id: "matar-paneer",
        name: "matar paneer",
        cuisines: ["North Indian"],
        meal_type: "curry",
        ingredients: ["paneer", "peas", "tomato", "onion", "spices"],
        popularity: "moderate",
        flavor_profile: ["savory", "spiced", "tomato-rich"],
    },
    {
        id: "malai-kofta",
        name: "malai kofta",
        cuisines: ["North Indian"],
        meal_type: "curry",
        ingredients: ["paneer", "potato", "cream", "tomato", "spices"],
        popularity: "moderate",
        flavor_profile: ["creamy", "rich", "mildly-spiced"],
    },
    {
        id: "kadhi-chawal",
        name: "kadhi chawal",
        cuisines: ["Gujarati", "Rajasthani", "North Indian"],
        meal_type: "rice_dish",
        ingredients: ["yogurt", "gram flour", "rice", "curry leaves", "spices"],
        popularity: "distinctive",
        flavor_profile: ["tangy", "savory", "comforting"],
    },
    {
        id: "sarson-da-saag",
        name: "sarson da saag",
        cuisines: ["Punjabi"],
        meal_type: "curry",
        ingredients: ["mustard greens", "spinach", "ginger", "butter", "cornmeal"],
        popularity: "distinctive",
        flavor_profile: ["earthy", "buttery", "hearty"],
    },
    {
        id: "amritsari-kulcha",
        name: "amritsari kulcha",
        cuisines: ["Amritsari", "Punjabi"],
        meal_type: "bread",
        ingredients: ["flour", "potato", "coriander", "butter", "onion"],
        popularity: "distinctive",
        flavor_profile: ["buttery", "stuffed", "savory"],
    },
    {
        id: "rogan-josh",
        name: "rogan josh",
        cuisines: ["Kashmiri"],
        meal_type: "curry",
        ingredients: ["lamb", "yogurt", "onion", "fennel", "spices"],
        popularity: "distinctive",
        flavor_profile: ["aromatic", "spiced", "rich"],
    },
    {
        id: "jalebi",
        name: "jalebi",
        cuisines: ["North Indian"],
        meal_type: "dessert",
        ingredients: ["flour", "yogurt", "sugar syrup", "saffron", "ghee"],
        popularity: "common",
        flavor_profile: ["sweet", "crispy", "syrupy"],
    },
    {
        id: "gulab-jamun",
        name: "gulab jamun",
        cuisines: ["North Indian"],
        meal_type: "dessert",
        ingredients: ["milk solids", "flour", "sugar syrup", "cardamom", "ghee"],
        popularity: "common",
        flavor_profile: ["sweet", "syrupy", "cardamom"],
    },
    {
        id: "rasmalai",
        name: "rasmalai",
        cuisines: ["Bengali"],
        meal_type: "dessert",
        ingredients: ["paneer", "milk", "sugar", "cardamom", "saffron"],
        popularity: "moderate",
        flavor_profile: ["sweet", "milky", "cardamom"],
    },
    {
        id: "kheer",
        name: "kheer",
        cuisines: ["North Indian"],
        meal_type: "dessert",
        ingredients: ["rice", "milk", "sugar", "cardamom", "nuts"],
        popularity: "common",
        flavor_profile: ["sweet", "milky", "cardamom"],
    },
    {
        id: "rabri",
        name: "rabri",
        cuisines: ["Rajasthani", "North Indian"],
        meal_type: "dessert",
        ingredients: ["milk", "sugar", "cardamom", "saffron", "nuts"],
        popularity: "distinctive",
        flavor_profile: ["sweet", "dense", "saffron"],
    },

    {
        id: "hummus",
        name: "hummus",
        cuisines: ["Lebanese", "Middle Eastern"],
        meal_type: "dip",
        ingredients: ["chickpeas", "tahini", "lemon", "garlic", "olive oil"],
        popularity: "common",
        flavor_profile: ["creamy", "nutty", "lemony"],
    },
    {
        id: "falafel",
        name: "falafel",
        cuisines: ["Lebanese", "Middle Eastern"],
        meal_type: "snack",
        ingredients: ["chickpeas", "parsley", "garlic", "cumin", "onion"],
        popularity: "common",
        flavor_profile: ["crispy", "herby", "savory"],
    },
    {
        id: "shawarma",
        name: "shawarma",
        cuisines: ["Lebanese", "Middle Eastern"],
        meal_type: "sandwich_wrap",
        ingredients: ["chicken", "pita", "garlic sauce", "pickles", "spices"],
        popularity: "common",
        flavor_profile: ["garlicky", "spiced", "savory"],
    },
    {
        id: "fattoush",
        name: "fattoush",
        cuisines: ["Lebanese", "Middle Eastern"],
        meal_type: "salad",
        ingredients: ["lettuce", "tomato", "cucumber", "pita chips", "sumac"],
        popularity: "distinctive",
        flavor_profile: ["fresh", "tangy", "crunchy"],
    },
    {
        id: "tabbouleh",
        name: "tabbouleh",
        cuisines: ["Lebanese", "Middle Eastern"],
        meal_type: "salad",
        ingredients: ["parsley", "bulgur", "tomato", "mint", "lemon"],
        popularity: "distinctive",
        flavor_profile: ["herby", "lemony", "fresh"],
    },
    {
        id: "kibbeh",
        name: "kibbeh",
        cuisines: ["Lebanese", "Middle Eastern"],
        meal_type: "snack",
        ingredients: ["bulgur", "minced meat", "onion", "pine nuts", "spices"],
        popularity: "distinctive",
        flavor_profile: ["spiced", "nutty", "savory"],
    },
    {
        id: "kofta-kebab",
        name: "kofta kebab",
        cuisines: ["Middle Eastern"],
        meal_type: "grill",
        ingredients: ["minced meat", "onion", "parsley", "cumin", "spices"],
        popularity: "moderate",
        flavor_profile: ["smoky", "spiced", "savory"],
    },
    {
        id: "shakshuka",
        name: "shakshuka",
        cuisines: ["Middle Eastern"],
        meal_type: "breakfast",
        ingredients: ["eggs", "tomato", "bell pepper", "onion", "spices"],
        popularity: "moderate",
        flavor_profile: ["tomato-rich", "spiced", "savory"],
    },

    {
        id: "burger",
        name: "burger",
        cuisines: ["American"],
        meal_type: "sandwich_wrap",
        ingredients: ["beef patty", "bun", "lettuce", "tomato", "cheese"],
        popularity: "common",
        flavor_profile: ["savory", "cheesy", "hearty"],
    },
    {
        id: "fried-chicken",
        name: "fried chicken",
        cuisines: ["American"],
        meal_type: "main_course",
        ingredients: ["chicken", "flour", "buttermilk", "paprika", "oil"],
        popularity: "common",
        flavor_profile: ["crispy", "savory", "rich"],
    },
    {
        id: "mac-and-cheese",
        name: "mac and cheese",
        cuisines: ["American"],
        meal_type: "main_course",
        ingredients: ["macaroni", "cheddar", "milk", "butter", "breadcrumbs"],
        popularity: "common",
        flavor_profile: ["creamy", "cheesy", "rich"],
    },
    {
        id: "barbecue-ribs",
        name: "barbecue ribs",
        cuisines: ["American"],
        meal_type: "grill",
        ingredients: ["pork ribs", "barbecue sauce", "garlic", "paprika", "brown sugar"],
        popularity: "moderate",
        flavor_profile: ["smoky", "sweet", "savory"],
    },
    {
        id: "hot-dog",
        name: "hot dog",
        cuisines: ["American"],
        meal_type: "sandwich_wrap",
        ingredients: ["sausage", "bun", "mustard", "ketchup", "onion"],
        popularity: "common",
        flavor_profile: ["salty", "savory", "simple"],
    },
    {
        id: "pancakes",
        name: "pancakes",
        cuisines: ["American"],
        meal_type: "breakfast",
        ingredients: ["flour", "milk", "egg", "butter", "maple syrup"],
        popularity: "common",
        flavor_profile: ["sweet", "buttery", "soft"],
    },
    {
        id: "grilled-cheese-sandwich",
        name: "grilled cheese sandwich",
        cuisines: ["American"],
        meal_type: "sandwich_wrap",
        ingredients: ["bread", "cheese", "butter"],
        popularity: "common",
        flavor_profile: ["cheesy", "buttery", "simple"],
    },

    {
        id: "sushi",
        name: "sushi",
        cuisines: ["Japanese"],
        meal_type: "rice_dish",
        ingredients: ["sushi rice", "nori", "seafood", "vinegar", "soy sauce"],
        popularity: "common",
        flavor_profile: ["clean", "briny", "vinegared"],
    },
    {
        id: "ramen",
        name: "ramen",
        cuisines: ["Japanese"],
        meal_type: "noodle_dish",
        ingredients: ["noodles", "broth", "pork", "egg", "scallion"],
        popularity: "common",
        flavor_profile: ["umami", "brothy", "savory"],
    },
    {
        id: "okonomiyaki",
        name: "okonomiyaki",
        cuisines: ["Japanese"],
        meal_type: "main_course",
        ingredients: ["cabbage", "flour", "egg", "pork", "sauce"],
        popularity: "distinctive",
        flavor_profile: ["savory", "sweet-sauce", "hearty"],
    },
    {
        id: "katsu-curry",
        name: "katsu curry",
        cuisines: ["Japanese"],
        meal_type: "curry",
        ingredients: ["breaded cutlet", "curry sauce", "rice", "flour", "egg"],
        popularity: "moderate",
        flavor_profile: ["crispy", "mildly-spiced", "savory"],
    },
    {
        id: "onigiri",
        name: "onigiri",
        cuisines: ["Japanese"],
        meal_type: "snack",
        ingredients: ["rice", "nori", "salmon", "sesame", "salt"],
        popularity: "distinctive",
        flavor_profile: ["savory", "seaweed", "simple"],
    },

    {
        id: "tacos",
        name: "tacos",
        cuisines: ["Mexican"],
        meal_type: "street_food",
        ingredients: ["tortillas", "meat", "onion", "cilantro", "salsa"],
        popularity: "common",
        flavor_profile: ["fresh", "savory", "spiced"],
    },
    {
        id: "burrito",
        name: "burrito",
        cuisines: ["Mexican"],
        meal_type: "sandwich_wrap",
        ingredients: ["tortilla", "rice", "beans", "meat", "salsa"],
        popularity: "common",
        flavor_profile: ["hearty", "savory", "spiced"],
    },
    {
        id: "quesadilla",
        name: "quesadilla",
        cuisines: ["Mexican"],
        meal_type: "snack",
        ingredients: ["tortilla", "cheese", "onion", "peppers", "salsa"],
        popularity: "common",
        flavor_profile: ["cheesy", "savory", "toasted"],
    },
    {
        id: "guacamole",
        name: "guacamole",
        cuisines: ["Mexican"],
        meal_type: "dip",
        ingredients: ["avocado", "lime", "onion", "cilantro", "chili"],
        popularity: "common",
        flavor_profile: ["creamy", "fresh", "lime"],
    },
    {
        id: "elote",
        name: "elote",
        cuisines: ["Mexican"],
        meal_type: "street_food",
        ingredients: ["corn", "mayo", "cheese", "chili", "lime"],
        popularity: "distinctive",
        flavor_profile: ["charred", "creamy", "tangy"],
    },
    {
        id: "nachos",
        name: "nachos",
        cuisines: ["Mexican"],
        meal_type: "snack",
        ingredients: ["tortilla chips", "cheese", "beans", "jalapeno", "salsa"],
        popularity: "common",
        flavor_profile: ["crunchy", "cheesy", "spiced"],
    },

    {
        id: "fresh-spring-rolls",
        name: "fresh spring rolls",
        cuisines: ["Vietnamese"],
        meal_type: "snack",
        ingredients: ["rice paper", "herbs", "shrimp", "vermicelli", "lettuce"],
        popularity: "distinctive",
        flavor_profile: ["fresh", "herby", "light"],
    },

    {
        id: "dumplings",
        name: "dumplings",
        cuisines: ["Chinese"],
        meal_type: "snack",
        ingredients: ["flour", "minced meat", "cabbage", "ginger", "soy sauce"],
        popularity: "common",
        flavor_profile: ["savory", "gingery", "umami"],
    },
    {
        id: "chow-mein",
        name: "chow mein",
        cuisines: ["Chinese"],
        meal_type: "noodle_dish",
        ingredients: ["noodles", "vegetables", "soy sauce", "meat", "scallion"],
        popularity: "common",
        flavor_profile: ["savory", "stir-fried", "umami"],
    },
    {
        id: "sweet-and-sour-pork",
        name: "sweet and sour pork",
        cuisines: ["Chinese"],
        meal_type: "main_course",
        ingredients: ["pork", "bell pepper", "pineapple", "vinegar", "sauce"],
        popularity: "moderate",
        flavor_profile: ["sweet", "tangy", "crispy"],
    },
    {
        id: "hot-pot",
        name: "hot pot",
        cuisines: ["Chinese"],
        meal_type: "soup",
        ingredients: ["broth", "meat", "tofu", "vegetables", "noodles"],
        popularity: "distinctive",
        flavor_profile: ["brothy", "communal", "savory"],
    },
    {
        id: "wonton-soup",
        name: "wonton soup",
        cuisines: ["Chinese"],
        meal_type: "soup",
        ingredients: ["wontons", "broth", "scallion", "ginger", "sesame oil"],
        popularity: "moderate",
        flavor_profile: ["brothy", "gingery", "light"],
    },
    {
        id: "fried-rice",
        name: "fried rice",
        cuisines: ["Chinese"],
        meal_type: "rice_dish",
        ingredients: ["rice", "egg", "vegetables", "soy sauce", "scallion"],
        popularity: "common",
        flavor_profile: ["savory", "stir-fried", "umami"],
    },

    {
        id: "croissant",
        name: "croissant",
        cuisines: ["French"],
        meal_type: "breakfast",
        ingredients: ["flour", "butter", "yeast", "milk", "sugar"],
        popularity: "common",
        flavor_profile: ["buttery", "flaky", "light"],
    },
    {
        id: "crepes",
        name: "crepes",
        cuisines: ["French"],
        meal_type: "breakfast",
        ingredients: ["flour", "milk", "egg", "butter", "sugar"],
        popularity: "common",
        flavor_profile: ["soft", "buttery", "light"],
    },
    {
        id: "ratatouille",
        name: "ratatouille",
        cuisines: ["French"],
        meal_type: "main_course",
        ingredients: ["eggplant", "zucchini", "tomato", "bell pepper", "herbs"],
        popularity: "distinctive",
        flavor_profile: ["vegetable-forward", "herby", "savory"],
    },

    {
        id: "doner-kebab",
        name: "doner kebab",
        cuisines: ["Turkish"],
        meal_type: "sandwich_wrap",
        ingredients: ["meat", "pita", "tomato", "onion", "yogurt sauce"],
        popularity: "moderate",
        flavor_profile: ["spiced", "savory", "garlicky"],
    },
    {
        id: "gyros",
        name: "gyros",
        cuisines: ["Greek"],
        meal_type: "sandwich_wrap",
        ingredients: ["pork", "pita", "tomato", "onion", "tzatziki"],
        popularity: "moderate",
        flavor_profile: ["savory", "herby", "garlicky"],
    },

    {
        id: "fish-and-chips",
        name: "fish and chips",
        cuisines: ["British"],
        meal_type: "main_course",
        ingredients: ["fish", "potato", "flour", "vinegar", "tartar sauce"],
        popularity: "common",
        flavor_profile: ["crispy", "salty", "savory"],
    },
    {
        id: "english-breakfast",
        name: "english breakfast",
        cuisines: ["British"],
        meal_type: "breakfast",
        ingredients: ["eggs", "sausage", "beans", "toast", "mushrooms"],
        popularity: "moderate",
        flavor_profile: ["hearty", "savory", "rich"],
    },
]

export const catalogById = new Map(catalog.map((item) => [item.id, item]))
